# Generated by Django 5.1.1 on 2024-10-08 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='author_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.authors'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books',
            name='genre_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.genre'),
            preserve_default=False,
        ),
    ]
