# Generated by Django 5.1.1 on 2024-10-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_books_author_id_books_genre_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
